logging.level.root: info
spring:
  liquibase:
    change-log: classpath:db/changelog.xml
    drop-first: false
    enabled: true
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver