logging.level.root: info
spring:
  liquibase:
    change-log: classpath:db/changelog.xml
    drop-first: false
    enabled: true
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver